baseURL = "https://dfares-plugins.netlify.app/"
languageCode = "en-us"
title = "Dark Forest ARES Plugins"
Paginate = 1000
googleAnalytics = ""
theme = "showcase"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]
staticDir = ["screenshots", "static", "javascript"]

[params]
  name = "Dark Forest ARES Plugins"
  author = "Dark Forest ARES Plugins"
  description = "A showcase of Dark Forest ARES plugins from the community!"
  message = "Welcome to the Dark Forest ARES Plugin showcase!"
  hideAutoMenu = false
  repo = "dfarchon/plugins"
  branch = "main"

[[menu.main]]
  name = "Submit plugin"
  url = "https://github.com/dfarchon/plugins#adding-your-plugin"

[social]
  twitter = "https://twitter.com/dfarchon"
